---
base_dir: data_partitions_64/part0/model
log_level: INFO
data:
  batch_size: 64
  dataset_dir: data_partitions_64/part0/
  val_batch_size: 1
  test_batch_size: 1
  validation_ratio: 0.1
  test_ratio: 0.2
  graph_pkl_filename: data_partitions_64/part0/adj_mat.pkl
  hdf_filename: data_partitions_64/part0/speed.h5

model:
  cl_decay_steps: 2000
  filter_type: random_walk
  horizon: 12
  input_dim: 2
  l1_decay: 0
  max_diffusion_step: 2
  num_nodes: 207
  num_rnn_layers: 2
  output_dim: 1
  rnn_units: 16
  seq_len: 12
  use_curriculum_learning: true

train:
  base_lr: 0.01
  dropout: 0
  epoch: 0
  epochs: 30
  epsilon: 1.0e-3
  global_step: 0
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 50
  steps: [20, 30, 40, 50]
  test_every_n_epochs: 10